### ISSUE TITLE
User apache commons cli to parse options

### ISSUE THREAD

**Issue by gpoppino** [berkelioar/ipchecknotifier#1]
Use the long options to specify the parameters to the command. For example:

```
$ ipchecknotifier -ip
```

```
$ ipchecknotifier -history
```

For this commons cli from Apache can be used: https://commons.apache.org/proper/commons-cli/

**Comment by gcanosa** [comment]
It's been implemented successfully by Geronimo and Gerardo. Issue closed. Commit: a22240420920ca53ce3c5f69566ae39d598ee31d
